# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do

    desc "Build the release artifact"
    lane :build_release do
        gradle(task: "clean bundleRelease", flags: "-PbuildNumber=#{options[:build_number]}")
    end

    desc "Run the project tests"
    lane :test do |options|
        gradle(task: "test")
  end

    desc "Run the project Linter"
    lane :lint do
       gradle(task: "detekt")
    end

    desc "Deploy a new version to the Google Play"
    lane :deploy do |options|
      gradle(task: "clean bundleRelease", flags: "-PbuildNumber=#{options[:build_number]}")
      supply(track: "beta")
    end
end
