name: Android CI/CD

on:
  push:
    branches: [ main ] # still running this on commit as I test all the time on android. Will update to nightly if this becomes too much
    paths:
      - 'androidApp/**'
      - 'core/**'
env:
  LIFT_BRO_ADMOB_APP_ID: ${{ secrets.LIFT_BRO_ADMOB_APP_ID }}
  LIFT_BRO_AD_UNIT_ID: ${{ secrets.LIFT_BRO_AD_UNIT_ID }}
  LIFT_BRO_SENTRY_DSN: ${{ secrets.LIFT_BRO_SENTRY_DSN }}
  REVENUE_CAT_API_KEY: ${{ secrets.REVENUE_CAT_API_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Install Maestro CLI (Add Maestro to PATH)
        run: |
          curl -Ls "https://get.maestro.mobile.dev" | bash
          echo "$HOME/.maestro/bin" >> $GITHUB_PATH

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: 17

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.2
          bundler-cache: true

      - name: Run linter
        run: fastlane lint
        
#      - name: Run tests
#        run: fastlane test

      - name: decode keystore
        id: decode_keystore
        uses: timheuer/base64-to-file@v1.2
        with:
          fileName: 'release.jks'
          fileDir: 'androidApp'
          encodedString: ${{ secrets.RELEASE_KEYSTORE }}

      - name: create-json
        id: create-json
        uses: jsdaniell/create-json@1.1.2
        with:
          name: "key.json"
          json: ${{ secrets.FASTLANE_JSON }}

      - name: Run fastlane deploy
        env:
          STORE_PASSWORD: ${{ secrets.KEYSTORE_PW }}
          KEY_ALIAS: ${{ secrets.KEYSTORE_USR }}
          KEY_PASSWORD: ${{ secrets.KEY_PW }}
        run: fastlane deploy build_number:$GITHUB_RUN_NUMBER

      - name: Upload Apk
        uses: actions/upload-artifact@v4
        with:
          name: assets
          path: app/build/outputs/bundle/release/app-release.aab